name: reusable workflows getting started
on:
  push:
    branches: main

jobs:
  base:
    uses: josefernandezatceiba/tagtest/.github/workflows/setup_build.yml@main
    with:
      app_name: oneapp
    
  additional-steps:
    needs: base
    runs-on: ubuntu-latest
    steps: 
      - name: zipping stuff
        working-directory: ./
        run: |
          pwd && ls -li
      
    
      
          
    
  
    
   
    
    
          
