name: reusable workflows getting started
on:
  push:
    branches: main

jobs:
  builds:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Cache yarn packages
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-
            
      - name: Build 
        working-directory: ./
        run: | 
          cd poc
          yarn build oneapp
          yarn build twoapp
          
