name: reusable workflows getting started
on:
  push:
    branches: main

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps: 
      - name: calling reusable workflow
        uses: ./.github/workflows/setup_build.yml
        with:
          app_name: oneapp
      - name: zip stuff
        working-directory: ./
        run: |
          pwd && ls -li
          zip -r -9 oneapp-${{ github.run_id }}.zip ./*   
    
      
          
    
  
    
   
    
    
          
