name: reusable workflows getting started
on:
  push:
    branches: main

jobs:
  build:
    uses: tagtest/.github/workflows/setup_build.yml@main
    with:
      app_name: oneapp
    
  
    
   
    
    
          
