name: reusable workflows getting started
on:
  push:
    branches: main

jobs:
  build:
    uses: ./.github/workflows/setup_build.yml
    with:
      app_name: oneapp
    
  
    
   
    
    
          
