name: reusable workflows getting started
on:
  push:
    branches: main

jobs:
  build:
    uses: ./.github/workflows/setup_build.yml
    with:
      app_name: oneapp
    
      
  zip_app:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: zip-app
        working-directory: ./
        run: |
          pwd && ls ./ -lia
    
  
    
   
    
    
          
